### ISSUE TITLE
Support for unsigned primitive types

### ISSUE THREAD

**Issue by vtalpaert** [nrjl/lcm_to_ros#1]
Thanks for the hard work, this project works just fine.

I was wondering if you plan to add support for unsigned values, I have an example here for republishing messages from ROS to LCM with the VelodynePacket message.
The message is defined as follow:

```
rosmsg show velodyne_msgs/VelodynePacket 
time stamp
uint8[1206] data
```

Only when I try to recreate this with your package I can get only as far as:

```
rosmsg show lcm_to_ros/velodyne_packet 
time stamp
int8[1206] data
```

With result in the expected error
`[ERROR] [1467982809.956284460]: Client [/lcm_to_ros/velodyne_packets_republisher] wants topic /lcm_to_ros/velodyne_packets to have datatype/md5sum [lcm_to_ros/velodyne_packet/08fc2f480f398e309323b41f1efa2fb9], but our version has [velodyne_msgs/VelodyneScan/50804fc9533a0e579e6322c04ae70566]. Dropping connection.`

I _could_ have an intermediate node to cast the data type for each point from unsigned to signed, but it doesn't seem right for the heavy amount of data I get in. Would you have any suggestion on how to solve this?

**Comment by nrjl** [comment]
Hi,

Unfortunately LCM doesn't support unsigned types, because they wanted to
maintain compatibility with Java which apparently doesn't have unsigned
types:

> "The integer types are all signed (as is necessary to ensure easy
> inter-operation with Java, which lacks unsigned types) and are encoded in
> network byte order."
> 
> https://lcm-proj.github.io/type_specification.html#type_specification_primitives

The LCM docs suggest using the byte type and then reinterpreting it at the
other end.

> "The type byte is encoded the same way as int8_t. However, there are
> instances in which buffers of data (such as a JPEG image) must be sent
> across the network. These buffers of data must be decoded by some
> additional software. The type byte can be used by a type designer to help
> convey the notion that the data is opaque, and should not be interpreted
> (literally) as an array of 8 bit integers."
> 
> https://lcm-proj.github.io/type_specification.html#type_specification_primitives

So I would suggest a similar approach, though I know it is clunky that way.
It should be fast though, since you'll just be recasting the pointer to the
array once, so it doesn't matter about the array size or anything like
that. You can directly edit the auto-generated republisher code too, and
putting the recast in there shouldn't be too bad. Just be aware that each
time you regenerate it it will get overwritten. Since you don't change the
message definitions very often this might not be a problem though. I can't
think of any easy way to do it otherwise, though I'm not a very good
software engineer, so if you can think of a possible way to do it then I'm
willing to try and code it up. Sorry about that, and let me know if you
think of a good way to solve this.

Thanks,
Nick

On Fri, Jul 8, 2016 at 6:12 AM, vtalpaert notifications@github.com wrote:

> Thanks for the hard work, this project works just fine.
> 
> I was wondering if you plan to add support for unsigned values, I have an
> example here for republishing messages from ROS to LCM with the
> VelodynePacket message.
> The message is defined as follow:
> 
> rosmsg show velodyne_msgs/VelodynePacket
> time stamp
> uint8[1206] data
> 
> Only when I try to recreate this with your package I can get only as far
> as:
> 
> rosmsg show lcm_to_ros/velodyne_packet
> time stamp
> int8[1206] data
> 
> With result in the expected error
> [ERROR] [1467982809.956284460]: Client
> [/lcm_to_ros/velodyne_packets_republisher] wants topic
> /lcm_to_ros/velodyne_packets to have datatype/md5sum
> [lcm_to_ros/velodyne_packet/08fc2f480f398e309323b41f1efa2fb9], but our
> version has [velodyne_msgs/VelodyneScan/50804fc9533a0e579e6322c04ae70566].
> Dropping connection.
> 
> I _could_ have an intermediate node to cast the data type for each point
> from unsigned to signed, but it doesn't seem right for the heavy amount of
> data I get in. Would you have any suggestion on how to solve this?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nrjl/lcm_to_ros/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AKLyK2mFx0xDoIWc98iA90bM7iDhscYlks5qTkypgaJpZM4JIBHi
> .

## 

Dr. Nicholas Lawrance
Postdoctoral Researcher
Robotic Decision Making Laboratory,
Oregon State University, Corvallis OR
Email: nicholas.lawrance@oregonstate.edu
